# Задача 0

Имеется калькулятор, который выполняет три операции:

1. Прибавить к числу X единицу.
2. Умножить число X на 2.
3. Умножить число X на 3.

Определите, какое наименьшее число операций необходимо для того, чтобы получить из числа 1 заданное число N.

**Примеры**

входные данные | выходные данные
---|---
1 | 0
5 | 3
32718 | 17

In [1]:
'''Your code here'''

'Your code here'

# Задача 1

Напишите функцию возврщающую n-ное число Фибоначчи.

In [2]:
def fib(n):
    if n == 0: return 0
    if n == 1: return 1
    return fib(n - 2) + fib(n - 1)


d = {0: 0, 1: 1}

def fib2(n):
    if n in d.keys():
        return d[n]
    else:
        fn = fib2(n - 2) + fib2(n - 1)
        d[n] = fn
        return fn
    
def fib3(n):
    d = {0: 0, 1: 1}
    for i in range(2, n + 1):
        d[i] = d[i - 1] + d[i - 2]
    
    return d[n]


fib3(1000000)

# Задача 2

Алгоритм вычисления значения функции $F(n)$, где $n$ – натуральное число, задан следующими соотношениями:
$$
F(n)=\begin{cases}
    n & \text{если }n≥2025, \\
    F(n)=F(n+1)−F(n+2)+7 & \text{если }n<2025.
\end{cases}
$$
Чему равно значение выражения $F(15)−F(24)$?

In [1]:
def f():
    d = {2025: 2025, 2026: 2026}
    for i in range(2024, 0, -1):
        d[i] = d[i + 1] - d[i + 2] + 7
    
    return d[15] - d[24]

# Задача 3

Имеется калькулятор, который выполняет три операции:

1. Прибавить к числу X единицу.
2. Умножить число X на 2.
3. Умножить число X на 3.

Определите кратчайшую последовательность операций, необходимую для получения из числа 1 заданное число N.

Входные данные
Программа получает на вход одно число N, не превосходящее 106.

Выходные данные
Выведите строку, состоящую из цифр "1", "2" или "3", обозначающих одну из трех указанных операций, которая получает из числа 1 число N за минимальное число операций. Если возможных минимальных решений несколько, выведите любое из них.

**Примеры**

входные данные | выходные данные
---|---
1 | 
5 | 121
562340 | 3333312222122213312

In [4]:
'''Your code here'''

'Your code here'

# Задача 4

Робот стоит в левом нижнем углу прямоугольного поля, в каждой клетке которого записано целое положительное число. За один ход робот может переместиться на одну клетку вправо или на одну клетку вверх.

Расход энергии на запуск робота равен числу, записанному в стартовой клетке. В дальнейшем расход энергии на шаг из одной клетки в другую равен абсолютной величине разности чисел, записанных в этих клетках.
Определите минимальный и максимальный расход энергии при переходе робота в правую верхнюю клетку поля. В ответе запишите два числа: сначала минимальный расход энергии, затем – максимальный.
Исходные данные записаны в файле 3.txt.

In [7]:
f = [list(map(int, s.split())) for s in open('3.txt').readlines()]

n = len(f)
m = len(f[0])

en = [[0] * m for _ in range(n)]
en[-1][0] = f[-1][0]

for i in range(1, m):
    en[-1][i] = abs(f[-1][i - 1] - f[-1][i]) + en[-1][i - 1]

for i in range(n - 2, -1, -1):
    en[i][0] = abs(f[i][0] - f[i + 1][0]) + en[i + 1][0]

for i in range(n - 2, -1, -1):
    for j in range(1, m):
        en[i][j] = min(abs(f[i][j] - f[i][j - 1]) + en[i][j - 1], 
                       abs(f[i][j] - f[i + 1][j]) + en[i + 1][j])

for s in en:
    print(*s)

en

531 526 476 469 448 467 474 443 478 560 552 526 565 499 479
517 458 461 454 432 455 478 415 428 497 498 521 564 473 471
499 407 411 438 411 445 451 404 468 529 439 462 529 461 469
430 403 406 423 374 391 387 395 464 465 423 458 461 436 466
422 374 386 378 344 379 382 388 396 398 411 438 435 435 462
374 358 363 345 335 366 380 366 419 379 392 392 418 423 427
339 341 342 316 326 314 344 341 399 367 390 458 461 434 427
317 360 307 299 296 296 334 324 325 337 344 387 431 421 416
313 329 291 257 286 300 346 306 328 337 350 360 362 411 413
262 314 249 257 289 274 305 298 314 323 321 328 335 371 386
242 243 248 255 267 262 272 253 276 332 299 340 342 409 428
187 254 216 183 221 247 222 238 263 287 288 321 384 409 420
135 198 178 131 175 199 218 246 249 326 336 393 400 396 406
116 116 119 125 125 194 229 230 278 337 326 349 362 389 399
61 73 94 128 161 198 202 237 247 295 312 388 402 461 464

[[531, 526, 476, 469, 448, 467, 474, 443, 478, 560, 552, 526, 565, 499, 479],
 [517, 458, 461, 454, 432, 455, 478, 415, 428, 497, 498, 521, 564, 473, 471],
 [499, 407, 411, 438, 411, 445, 451, 404, 468, 529, 439, 462, 529, 461, 469],
 [430, 403, 406, 423, 374, 391, 387, 395, 464, 465, 423, 458, 461, 436, 466],
 [422, 374, 386, 378, 344, 379, 382, 388, 396, 398, 411, 438, 435, 435, 462],
 [374, 358, 363, 345, 335, 366, 380, 366, 419, 379, 392, 392, 418, 423, 427],
 [339, 341, 342, 316, 326, 314, 344, 341, 399, 367, 390, 458, 461, 434, 427],
 [317, 360, 307, 299, 296, 296, 334, 324, 325, 337, 344, 387, 431, 421, 416],
 [313, 329, 291, 257, 286, 300, 346, 306, 328, 337, 350, 360, 362, 411, 413],
 [262, 314, 249, 257, 289, 274, 305, 298, 314, 323, 321, 328, 335, 371, 386],
 [242, 243, 248, 255, 267, 262, 272, 253, 276, 332, 299, 340, 342, 409, 428],
 [187, 254, 216, 183, 221, 247, 222, 238, 263, 287, 288, 321, 384, 409, 420],
 [135, 198, 178, 131, 175, 199, 218, 246, 249, 326, 336, 393, 400, 396, 406],
 [116, 116, 119, 125, 125, 194, 229, 230, 278, 337, 326, 349, 362, 389, 399],
 [61, 73, 94, 128, 161, 198, 202, 237, 247, 295, 312, 388, 402, 461, 464]]

# Задача 5

Даны две последовательности, требуется найти длину их наибольшей общей подпоследовательности.

In [11]:
def t5(a: str, b:str) -> int:
    n, m = len(a), len(b)

    dp = [[0] * m for _ in range(n)]

    for i in range(n):
        for j in range(m):
            if a[i] == b[j]:
                dp[i][j] = dp[i - 1][j - 1] + 1
            else:
                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])

    return dp
t5('12345', '27325')

[[0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1],
 [1, 1, 2, 2, 2],
 [1, 1, 2, 2, 2],
 [1, 1, 2, 2, 3]]

# Задача 6. Расстояние по Левенштейну

Дана текстовая строка. С ней можно выполнять следующие операции:

1. Заменить один символ строки на другой символ.

2. Удалить один произвольный символ.

3. Вставить произвольный символ в произвольное место строки.

Например, при помощи первой операции из строки "СОК" можно получить строку "СУК", при помощи второй операции - строку "ОК", при помощи третьей операции - строку "СТОК.

Минимальное количество таких операций, при помощи которых можно из одной строки получить другую, называется стоимостью редактирования или расстоянием Левенштейна.

Определите расстояние Левенштейна для двух данных строк.

**Пример**
входные данные | выходные данные
---|---
ABCDEFGH ACDEXGIH | 3

In [ ]:
def t6(a: str, b:str) -> int:
    n, m = len(a), len(b)

    dp = [[0] * m for _ in range(n)]

    for i in range(n):
        for j in range(m):
            if a[i] == b[j]:

# Задача 7

Дана последовательность, требуется найти длину её наибольшей возрастающей подпоследовательности. Подпоследовательностью последовательности называется некоторый набор её элементов, не обязательно стоящих подряд.

**Пример**
входные данные | выходные данные
---|---
3 29 5 5 28 6 | 3

In [7]:
'''Your code here'''

'Your code here'

# Задача 8

Первая строка входа содержит целые числа $1≤W≤10$ и $1≤n≤300$ — вместимость рюкзака и число золотых слитков. Следующая строка содержит $n$ целых чисел $0≤w_1,…,w_n≤10^5$, задающих веса слитков. 

Найдите максимальный вес золота, который можно унести в рюкзаке.

**Пример**
входные данные | выходные данные
---|---
10 3
1 4 8 | 9

In [8]:
'''Your code here'''

'Your code here'